// POST ACTION TYPES
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const LOAD_POSTS = 'LOAD_POSTS';

// COMMENT ACTION TYPES
export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
